export { default as HomeSvg } from './HomeSvg/HomeSvg'
export { default as DestinationsSvg } from './DestinationsSvg/DestinationsSvg'
export { default as PlansSvg } from './PlansSvg/PlansSvg'
export { default as CoupleTourSvg } from './CoupleTourSvg/CoupleTourSvg'
export { default as BookingSvg } from './BookingSvg/BookingSvg'